// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EditUser struct {
	ID        string `json:"id"`
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
	Phone     string `json:"Phone"`
	Address   string `json:"Address"`
}

type NewUser struct {
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
	Age       int    `json:"Age"`
	Phone     string `json:"Phone"`
	Address   string `json:"Address"`
}

type User struct {
	ID        string `json:"id" bson:"_id"`
	FirstName string `json:"FirstName"`
	LastName  string `json:"LastName"`
	Age       int    `json:"Age"`
	Phone     string `json:"Phone"`
	Address   string `json:"Address"`
}
